import './global.css';
import { SuperTokensProvider } from './components/supertokens-provider';
import { Container, Navbar } from '@tbergq/components';
import Link from 'next/link';
import Logout from './components/logout';
import * as Sentry from '@sentry/nextjs';
import type { Metadata } from 'next';

export function generateMetadata(): Metadata {
  return {
    title: 'Welcome to trainingjournal',
    description: 'Generated by create-nx-workspace',
    other: {
      ...Sentry.getTraceData(),
    },
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <SuperTokensProvider>
        <body>
          <title>Trainingjournal</title>
          <Navbar
            left={
              <Link className="Navbar__brand" href="/home">
                Trainingjournal
              </Link>
            }
            right={<Logout />}
          />
          <Container>
            <div className="layout__app-container">{children}</div>
          </Container>
        </body>
      </SuperTokensProvider>
    </html>
  );
}
